### ISSUE TITLE
Add dark/light theme mode

### ISSUE THREAD

**Issue by dhairyachandra** [dhairyachandra/Health-GPT#1]
I would like to have the option to switch between dark and light theme modes for improved usability and user experience. The dark theme would be particularly useful for users who work in low-light environments or suffer from eye strain. On the other hand, the light theme would be more appropriate for users who prefer a brighter interface or work in well-lit environments.

To implement this feature, we could add a toggle button to the settings menu that allows the user to switch between the two modes. We could also offer an automatic mode that switches between the two themes based on the user's device settings.

This feature would not only improve the user experience but also make the application more accessible to a wider range of users. I believe it would be a valuable addition to the application and would benefit its user base.

Thank you for considering my request.

**Comment by whosjorge23** [comment]
Hi, if you create the branch I can help you

**Comment by dhairyachandra** [comment]
Thank you @whosjorge23.
